### ISSUE TITLE
Some parts with rendering issues

### ISSUE THREAD

**Issue by mzwaal** [pixeljetstream/ldrawloader#4]
This file contains a few parts that have rendering issues that are visible in the ldrawloader_viewer.

Some have gaps in surfaces with geometry based patterns and others are more generic.

Complete library update 2023-06 can be used to reproduce.

```
0 Name: New Model.ldr
1 7 -110 -48 50 1 0 0 0 1 0 0 0 1 3479.dat
1 1 0 -8 0 1 0 0 0 1 0 0 0 1 4079.dat
1 7 69.999 -40.0018 -0.0098 1 0.000026 0 -0.000026 1 -0.000246 0 0.000246 1 3846p4g.dat
1 7 140 0 0 -1 0 0 0 -0.707107 0.707107 0 0.707107 0.707107 2582p68.dat
1 15 -60 -24 0 1 0 0 0 1 0 0 0 1 973p6e.dat
1 14 300 -72 -20 1 0 0 0 1 0 0 0 1 2583.dat
1 7 430 -24 -0 1 0 -0 0 1 0 0 0 1 3144.dat
1 1 -170 -24 10 1 0 0 0 1 0 0 0 1 3004p90.dat
```

Suggestion, perhaps implement complex material in the viewer for drawing render parts for debugging patterns. The grey panel in file has a pattern which is currently not visible in the viewer and has an error.

**Comment by pixeljetstream** [comment]
improved the situation at least basic parts look good, renderparts still show issues on some.

**Comment by pixeljetstream** [comment]
this commit https://github.com/pixeljetstream/ldrawloader_viewer/commit/937991df586ef7e35f9464a7a45870c3563a528f to the viewer also enables complex material support

![image](https://github.com/pixeljetstream/ldrawloader/assets/640162/e3bc760e-37d4-434f-bfc8-091863eb26f8)

**Comment by mzwaal** [comment]
Nice! I can confirm it works in the viewer and also in my application.
