### ISSUE TITLE
A part that is rendered in the main color (16) gets another color (9 Light Blue)

### ISSUE THREAD

**Issue by mzwaal** [pixeljetstream/ldrawloader#5]
If you render this modified mpd example file with the ldrawloader then you will see 2 light blue houses and 3 red ones. If you render it with LeoCAD you wil see 1 light yellow (16) a light blue (9) and 3 red houses.

It looks like the triangles of the render parts get material 9 in stead of LDR_MATERIALID_INHERIT = 16 when rendered with that material. If I render a part with material 16 then I expect that material back for the non complex cases.

Can you confirm this issue or is it working as expected and am I missing something?

--------

The attachment is a modified mpd example of 5 houses. Three are red, one is light blue (9) and one is in the main color (16) which is also an actually defined color.

```
0 FILE main.ldr
0 
0 Name: main.ldr
0 Author: 
1 7 0 0 0 1 0 0 0 1 0 0 0 1 819.dat
1 4 80 -8 70 1 0 0 0 1 0 0 0 1 house.ldr
1 4 -70 -8 20 0 0 -1 0 1 0 1 0 0 house.ldr
1 4 50 -8 -20 0 0 -1 0 1 0 1 0 0 house.ldr
1 9 0 -8 -30 1 0 0 0 1 0 0 0 1 house.ldr
1 16 -20 -8 70 1 0 0 0 1 0 0 0 1 house.ldr

0 NOFILE

0 FILE house.ldr
0 
0 Name: house.ldr
0 Author: 
1 16 0 0 0 1 0 0 0 1 0 0 0 1 3023.dat
1 16 0 -24 0 1 0 0 0 1 0 0 0 1 3065.dat
1 16 0 -48 0 1 0 0 0 1 0 0 0 1 3065.dat
1 16 0 -72 0 0 0 -1 0 1 0 1 0 0 3044b.dat

0 NOFILE
```

**Comment by pixeljetstream** [comment]
there was indeed a bug that I passed through the wrong enum from top-level, which by chance resulted in the material "9" being used. https://github.com/pixeljetstream/ldrawloader/commit/31b689eb94d551cf36a59cf960265342a942d839 should fix it.

The viewer also allows setting the inheritance color dynamically. And indeed it's a good idea to add complex material support to it. Although I might switch to using Vulkan for that and improve the overall viewer. Picking etc. could be useful.

**Comment by mzwaal** [comment]
Great, I have confirmed it is working. Nice touches to the viewer too!

A feature I would like is geometry simplification on model level, that would make a big wall for example cheaper to render. My use case is is rendering the maximum amount of models in real time. I don't use the chamfer feature for that reason. Also full support for all the official parts would be great.

Also for non transparent parts, there is a lot of stuff inside bricks that should be culled when bricks are stacked.

There are more things I can think of. What would be the best way for you to receive feedback/feature request that are not issues per se?

**Comment by pixeljetstream** [comment]
great to hear. This library mostly focuses on just supplying the model data. I haven't tried brute-force loading all parts. Maybe that is something the viewer needs to get a mode for. Sort of automatically rendering parts and then one could visually inspect what broke/crashed. filed https://github.com/pixeljetstream/ldrawloader_viewer/issues/1

Discussing a rendering system is a bit off topic , though let's use another issue https://github.com/pixeljetstream/ldrawloader/issues/6
